services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: syaofox/homer:2.5
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./config:/config 

# 定义volumes
volumes:
  config:
    # 这是一个命名卷，Docker会自动管理 