services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: syaofox/homer:2.6
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - DOCKER_CONTAINER=true
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - HOST=0.0.0.0
      - PORT=8080
      - MAX_CONTENT_LENGTH=16777216
      - CACHE_TTL=30
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config 

# 定义volumes
volumes:
  config:
    # 这是一个命名卷，Docker会自动管理 